### PR TITLE
Ouroboros 1st purpose

### PR DESCRIPTION
**Pull request by maiwann**

### CODE REVIEW

**Comment by Sigafoos** [comment]
Does this get rid of the animation effect of clicking the boost button?

**Comment by Aldarone** [comment]
Here is the result for now : 

capture d ecran_2017-04-27_22-49-05

It's a bit smaller than the original and I think you can go a bit thicker too.

**Comment by Aldarone** [comment]
It looks awesome ❤️ 

capture d ecran_2017-04-28_07-20-07

**Comment by Aldarone** [comment]
https://gfycat.com/ShockingMaleCur

The frames are a not quite aligned, the display box is 19px height and 22px wide.

**Comment by Aldarone** [comment]
whoppingcraftyargali

Almost !

**Comment by Aldarone** [comment]
neatweeklyfennecfox

Lol now it's the other way around. It's good enough for me if you got tired of tweaking one pixel a day 😆

**Comment by Aldarone** [comment]
fastequatorialconey

**Comment by Aldarone** [comment]
You
Are
Awesome

**Comment by Aldarone** [comment]
😞

**Comment by Aldarone** [comment]
Puuuurrrfect

**Comment by maiwann** [comment]
Do we keep that one ?

**Comment by Aldarone** [comment]
Yeah it's great !

I'm gonna optimize it and include it properly. Can you give me write access on your branch by editing the pull request and checking this field ?

capture d ecran_2017-04-29_13-05-37

**Comment by maiwann** [comment]
Done ? :x

**Comment by Aldarone** [comment]
Sorry for the explosions in your notification column. 😆

**Comment by maiwann** [comment]
It's soooooooooo coooooool :3

**Pull request closed without merging**
